import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { Search } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable}`}
      >
        <header className="w-screen h-[100px] bg-white flex justify-around items-center">
          <Link href="/">
            <Image
              src={'/6d33e927df1154b48d68502eecb49558d9041c01 (1).png'}
              alt="Logo"
              width={150}
              height={130}
            />
          </Link>
          <div className="h-[35px] w-[400px] border rounded-4xl flex items-center px-1">
            <Search className="w-[25] h-[25]"/>
          </div>
          <Image 
            src={'/52a6736dcec774265bb0e51ae213b8c520743bac (1).png'}
            alt="Brasil"
            width={25}
            height={25}
            className="rounded-full h-[25px]"
          />
        </header>
        <div className="h-[45px] w-screen bg-neutral-200 flex justify-center">
          {/* <Link
            href={'/'}
            className="relative bg-emerald-900 top-[-3px] py-[2px]"
          >
            Início
          </Link> */}
        </div>
        <div className="w-screen h-[3px] bg-emerald-900"></div>
        <main>
          {children}
        </main>
        <footer>
            <div className="w-screen h-[80px] flex justify-end items-end bg-orange-950">
              <div className="w-screen h-full flex items-center justify-center">
                <p className="text-white">Sobre a Tupi Games</p>
              </div>
              <Image
                src={'/24db0d39fc1f34b4a64a82d1253383835d722123.png'}
                alt="Footer"
                width={110}
                height={100}
                className="absolute"
              />
            </div>
            <div className="py-[60px] px-[40px]">
              <p>A TupiGames é uma plataforma de jogos educacionais criada com o objetivo de valorizar e fortalecer a cultura indígena, especialmente o povo Guarani. A iniciativa nasceu a partir de uma visita realizada por professores da Biopark Educação a escolas que atendem comunidades indígenas.
Durante essa visita, foi possível observar uma realidade preocupante: os conteúdos oferecidos a esses alunos são superficiais quando comparados ao currículo padrão da educação brasileira. Além disso, há uma carência significativa de materiais que respeitem e incluam a cultura e o idioma Guarani, principal língua dessas comunidades.
Diante desse cenário, surgiu a ideia de desenvolver, junto aos estudantes da faculdade, uma plataforma inovadora que atendesse essa demanda. Assim nasceu o projeto TupiGames, com o propósito de oferecer jogos educativos e interativos, bilíngues (Guarani e Português), que respeitam e valorizam a identidade indígena.
Nosso objetivo é tornar o processo de ensino-aprendizagem mais rico, acessível e divertido, complementando o excelente trabalho já realizado pelos professores locais com recursos que dialogam diretamente com a realidade cultural dos alunos.</p>
            </div>
        </footer>
      </body>
    </html>
  );
}
